import {
  ListChecks,
  MessagesSquare,
  FileText,
  HeartHandshake,
  ClipboardList,
  MessageCircle,
  FileSpreadsheet,
  Search,
  GraduationCap,
  PenLine,
  ShieldCheck,
  MessageSquareText,
  LayoutGrid,
  BookOpenCheck,
  Palette,
  Megaphone,
  Headset,
  type LucideIcon,
} from 'lucide-react'

/** Maps the icon-name strings stored in content data to the actual Lucide components. */
export const iconRegistry: Record<string, LucideIcon> = {
  ListChecks,
  MessagesSquare,
  FileText,
  HeartHandshake,
  ClipboardList,
  MessageCircle,
  FileSpreadsheet,
  Search,
  GraduationCap,
  PenLine,
  ShieldCheck,
  MessageSquareText,
  LayoutGrid,
  BookOpenCheck,
  Palette,
  Megaphone,
  Headset,
}
